### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by InkVisible** [NoffearrDeathProjecT/DeathCore_3.3.5#1]
hello, where can I download the database for DeathCore_3.3.5?

**Comment by Noffearr** [comment]
Coming soon!
I'm adding some new scripts, longer if you want to test it without these new scripts can download the same by clicking the link below:

DeathCore_3.3.5a_Databases
https://mega.co.nz/#!ztUHXBQA!NM69VTlgSviJ-B1pNeJOO8ML3xXkk_WkmfTNS4Ll4eo

**Comment by InkVisible** [comment]
Thanks, I'll take a look without these new scripts :)

**Comment by Noffearr** [comment]
Thank you very much @InkVisible! To test my project, surely will have some bug, if possible reporting to our team!
