### ISSUE TITLE
Why i died and not be teleported to graveyard

### ISSUE THREAD

**Issue by planee** [NoffearrDeathProjecT/DeathCore_3.3.5#3]
as title?!my ghost is stand on my died body.where hack?

**Comment by Noffearr** [comment]
Yes indeed I removed it to not have to go the cemetery to resurrect the character!

**Comment by planee** [comment]
........................can you tell me where is the hack ,need to make a config to control it!

**Comment by Noffearr** [comment]
What do you friend? Control what? Do you want when the character dies he goes to the cemetery?

**Comment by planee** [comment]
of course,i want go cemetery

**Comment by Noffearr** [comment]
I took it in my project because I think better to die and it's close to the body to be born! If case you want to die and go to the cemetery look for another project!
